eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # ProductService Route
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product

        # OrderService Route
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order

