name: microservices-demo
services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - /data/postgres
    ports:
      - "5432:5432"
#    networks:
#      driver: bridge
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - /data/db

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.3
    command: ['start-dev', "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    volumes:
      - ./realms/:/opt/keycloak/data/import/

    ports:
      - 8181:8080
    depends_on:
      - postgres

