server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/order-service
    password: 'postgres'
  cloud:
    discovery:
      enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    hostname: order-service

application-properties:
  inventory-url: "http://inventory-service:8082"
