server:
  port: 0

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    hostname: product-service
#host-docker-internal dan nasıl erişim sağlanır araştırılacak.tüm service ler tek tek host dosyasına yazılmamalı